### ISSUE TITLE
Dunst files missing

### ISSUE THREAD

**Issue by GixoXYZ** [rchrdwllm/dotfiles#1]
Hello!
I love your setup, it looks really nice. However, it seems that the images and files used to setup dunst are missing.
Thank you for your work. :)

**Comment by rchrdwllm** [comment]
Hi! Sorry for noticing this a little too late. I don't think I used dunst in my rice, as far as I remember, I don't really have any files for configuring it.

**Comment by GixoXYZ** [comment]
Hey there! Absolutely no worries! I saw some references to dunst in the scripts and that's why I asked, but regardless, I appreciate your clarification. Also thanks again for your work, it really is an awesome looking rice. :)
